# Generated by Django 5.2.14 on 2026-06-27 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo')], max_length=10, verbose_name='tipo')),
                ('arquivo', models.FileField(upload_to='midias/', verbose_name='arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'mídia',
                'verbose_name_plural': 'mídias',
                'ordering': ['-criado_em'],
            },
        ),
    ]
